/*----- PROTECTED REGION ID(VideoCaptureDS.h) ENABLED START -----*/
//=============================================================================
//
// file :        VideoCaptureDS.h
//
// description : Include file for the VideoCaptureDS class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef VideoCaptureDS_H
#define VideoCaptureDS_H

#include <tango.h>

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>


/*----- PROTECTED REGION END -----*/	//	VideoCaptureDS.h

/**
 *  VideoCaptureDS class description:
 *    
 */

namespace VideoCaptureDS_ns
{
/*----- PROTECTED REGION ID(VideoCaptureDS::Additional Class Declarations) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDS::Additional Class Declarations

class VideoCaptureDS : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(VideoCaptureDS::Data Members) ENABLED START -----*/

// Camera
cv::VideoCapture* cv_cam;

// Image that is shown if cannot get image from camera
cv::Mat* image_no_image;

// Parameters for jpeg incoding with opencv
//std::vector<int> jpeg_incode_params;

Tango::EncodedAttribute jpeg;

enum class CameraMode : unsigned char { None, RGB, BGR, Grayscale } cam_mode;

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDS::Data Members

//	Device property data members
public:
	//	Source:	
	Tango::DevUShort	source;
	//	Mode:	
	string	mode;
	//	Height:	
	Tango::DevUShort	height;
	//	Width:	
	Tango::DevUShort	width;
	//	JpegQuality:	
	Tango::DevUShort	jpegQuality;

//	Attribute data members
public:
	Tango::DevEncoded	*attr_Jpeg_read;
	Tango::DevUChar	*attr_Frame_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	VideoCaptureDS(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	VideoCaptureDS(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	VideoCaptureDS(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~VideoCaptureDS() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : VideoCaptureDS::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Jpeg related methods
 *	Description: 
 *
 *	Data type:	Tango::DevEncoded
 *	Attr type:	Scalar
 */
	virtual void read_Jpeg(Tango::Attribute &attr);
	virtual bool is_Jpeg_allowed(Tango::AttReqType type);
/**
 *	Attribute Frame related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Image max = 3840 x 720
 */
	virtual void read_Frame(Tango::Attribute &attr);
	virtual bool is_Frame_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : VideoCaptureDS::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command Capture related method
	 *	Description: 
	 *
	 */
	virtual void capture();
	virtual bool is_Capture_allowed(const CORBA::Any &any);
	/**
	 *	Command Reconnect related method
	 *	Description: 
	 *
	 */
	virtual void reconnect();
	virtual bool is_Reconnect_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : VideoCaptureDS::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(VideoCaptureDS::Additional Method prototypes) ENABLED START -----*/

private:

	// Recreating the video capture according to device properties
	void update_cv_cam();

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDS::Additional Method prototypes
};

/*----- PROTECTED REGION ID(VideoCaptureDS::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDS::Additional Classes Definitions

}	//	End of namespace

#endif   //	VideoCaptureDS_H
