/*----- PROTECTED REGION ID(VideoCaptureDSClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        VideoCaptureDSClass.cpp
//
// description : C++ source for the VideoCaptureDSClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the VideoCaptureDS once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <VideoCaptureDSClass.h>

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass.cpp

//-------------------------------------------------------------------
/**
 *	Create VideoCaptureDSClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_VideoCaptureDS_class(const char *name) {
		return VideoCaptureDS_ns::VideoCaptureDSClass::init(name);
	}
}

namespace VideoCaptureDS_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
VideoCaptureDSClass *VideoCaptureDSClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::VideoCaptureDSClass(string &s)
 * description : 	constructor for the VideoCaptureDSClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
VideoCaptureDSClass::VideoCaptureDSClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering VideoCaptureDSClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(VideoCaptureDSClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::constructor

	cout2 << "Leaving VideoCaptureDSClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::~VideoCaptureDSClass()
 * description : 	destructor for the VideoCaptureDSClass
 */
//--------------------------------------------------------
VideoCaptureDSClass::~VideoCaptureDSClass()
{
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
VideoCaptureDSClass *VideoCaptureDSClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new VideoCaptureDSClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
VideoCaptureDSClass *VideoCaptureDSClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		CaptureClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CaptureClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CaptureClass::execute(): arrived" << endl;
	((static_cast<VideoCaptureDS *>(device))->capture());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReconnectClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReconnectClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ReconnectClass::execute(): arrived" << endl;
	((static_cast<VideoCaptureDS *>(device))->reconnect());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum VideoCaptureDSClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum VideoCaptureDSClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum VideoCaptureDSClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void VideoCaptureDSClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "Source";
	prop_desc = "Webcam index";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Mode";
	prop_desc = "Camera mode\nValues:\n1. RGB or rgb\n2. BGR or bgr\n3. Grayscale or grayscale";
	prop_def  = "RGB";
	vect_data.clear();
	vect_data.push_back("RGB");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Height";
	prop_desc = "Height of image captured from webcam";
	prop_def  = "720";
	vect_data.clear();
	vect_data.push_back("720");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Width";
	prop_desc = "Width of image captured from webcam";
	prop_def  = "1280";
	vect_data.clear();
	vect_data.push_back("1280");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "JpegQuality";
	prop_desc = "Quality of jpeg compression of image from webcam";
	prop_def  = "50";
	vect_data.clear();
	vect_data.push_back("50");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Threshold";
	prop_desc = "Threshold of contour finding algorithm";
	prop_def  = "25";
	vect_data.clear();
	vect_data.push_back("25");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MinContourArea";
	prop_desc = "";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void VideoCaptureDSClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("VideoCaptureDS");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void VideoCaptureDSClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new VideoCaptureDS(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		VideoCaptureDS *dev = static_cast<VideoCaptureDS *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(VideoCaptureDSClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void VideoCaptureDSClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::attribute_factory_before
	//	Attribute : Jpeg
	JpegAttrib	*jpeg = new JpegAttrib();
	Tango::UserDefaultAttrProp	jpeg_prop;
	//	description	not set for Jpeg
	//	label	not set for Jpeg
	//	unit	not set for Jpeg
	//	standard_unit	not set for Jpeg
	//	display_unit	not set for Jpeg
	//	format	not set for Jpeg
	//	max_value	not set for Jpeg
	//	min_value	not set for Jpeg
	//	max_alarm	not set for Jpeg
	//	min_alarm	not set for Jpeg
	//	max_warning	not set for Jpeg
	//	min_warning	not set for Jpeg
	//	delta_t	not set for Jpeg
	//	delta_val	not set for Jpeg
	
	jpeg->set_default_properties(jpeg_prop);
	//	Not Polled
	jpeg->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	jpeg->set_change_event(true, false);
	att_list.push_back(jpeg);

	//	Attribute : ContourInfo
	ContourInfoAttrib	*contourinfo = new ContourInfoAttrib();
	Tango::UserDefaultAttrProp	contourinfo_prop;
	//	description	not set for ContourInfo
	//	label	not set for ContourInfo
	//	unit	not set for ContourInfo
	//	standard_unit	not set for ContourInfo
	//	display_unit	not set for ContourInfo
	//	format	not set for ContourInfo
	//	max_value	not set for ContourInfo
	//	min_value	not set for ContourInfo
	//	max_alarm	not set for ContourInfo
	//	min_alarm	not set for ContourInfo
	//	max_warning	not set for ContourInfo
	//	min_warning	not set for ContourInfo
	//	delta_t	not set for ContourInfo
	//	delta_val	not set for ContourInfo
	
	contourinfo->set_default_properties(contourinfo_prop);
	//	Not Polled
	contourinfo->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(contourinfo);

	//	Attribute : Threshold
	ThresholdAttrib	*threshold = new ThresholdAttrib();
	Tango::UserDefaultAttrProp	threshold_prop;
	//	description	not set for Threshold
	//	label	not set for Threshold
	//	unit	not set for Threshold
	//	standard_unit	not set for Threshold
	//	display_unit	not set for Threshold
	//	format	not set for Threshold
	//	max_value	not set for Threshold
	//	min_value	not set for Threshold
	//	max_alarm	not set for Threshold
	//	min_alarm	not set for Threshold
	//	max_warning	not set for Threshold
	//	min_warning	not set for Threshold
	//	delta_t	not set for Threshold
	//	delta_val	not set for Threshold
	
	threshold->set_default_properties(threshold_prop);
	//	Not Polled
	threshold->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(threshold);

	//	Attribute : Ruler
	RulerAttrib	*ruler = new RulerAttrib();
	Tango::UserDefaultAttrProp	ruler_prop;
	//	description	not set for Ruler
	//	label	not set for Ruler
	//	unit	not set for Ruler
	//	standard_unit	not set for Ruler
	//	display_unit	not set for Ruler
	//	format	not set for Ruler
	//	max_value	not set for Ruler
	//	min_value	not set for Ruler
	//	max_alarm	not set for Ruler
	//	min_alarm	not set for Ruler
	//	max_warning	not set for Ruler
	//	min_warning	not set for Ruler
	//	delta_t	not set for Ruler
	//	delta_val	not set for Ruler
	
	ruler->set_default_properties(ruler_prop);
	//	Not Polled
	ruler->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(ruler);

	//	Attribute : MinContourArea
	MinContourAreaAttrib	*mincontourarea = new MinContourAreaAttrib();
	Tango::UserDefaultAttrProp	mincontourarea_prop;
	//	description	not set for MinContourArea
	//	label	not set for MinContourArea
	//	unit	not set for MinContourArea
	//	standard_unit	not set for MinContourArea
	//	display_unit	not set for MinContourArea
	//	format	not set for MinContourArea
	//	max_value	not set for MinContourArea
	//	min_value	not set for MinContourArea
	//	max_alarm	not set for MinContourArea
	//	min_alarm	not set for MinContourArea
	//	max_warning	not set for MinContourArea
	//	min_warning	not set for MinContourArea
	//	delta_t	not set for MinContourArea
	//	delta_val	not set for MinContourArea
	
	mincontourarea->set_default_properties(mincontourarea_prop);
	//	Not Polled
	mincontourarea->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(mincontourarea);

	//	Attribute : Frame
	FrameAttrib	*frame = new FrameAttrib();
	Tango::UserDefaultAttrProp	frame_prop;
	//	description	not set for Frame
	//	label	not set for Frame
	//	unit	not set for Frame
	//	standard_unit	not set for Frame
	//	display_unit	not set for Frame
	//	format	not set for Frame
	//	max_value	not set for Frame
	//	min_value	not set for Frame
	//	max_alarm	not set for Frame
	//	min_alarm	not set for Frame
	//	max_warning	not set for Frame
	//	min_warning	not set for Frame
	//	delta_t	not set for Frame
	//	delta_val	not set for Frame
	
	frame->set_default_properties(frame_prop);
	//	Not Polled
	frame->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	frame->set_change_event(true, false);
	att_list.push_back(frame);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void VideoCaptureDSClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::pipe_factory_before
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void VideoCaptureDSClass::command_factory()
{
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::command_factory_before


	//	Command Capture
	CaptureClass	*pCaptureCmd =
		new CaptureClass("Capture",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCaptureCmd);

	//	Command Reconnect
	ReconnectClass	*pReconnectCmd =
		new ReconnectClass("Reconnect",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReconnectCmd);

	/*----- PROTECTED REGION ID(VideoCaptureDSClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void VideoCaptureDSClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(VideoCaptureDSClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		VideoCaptureDSClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void VideoCaptureDSClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		VideoCaptureDS *dev = static_cast<VideoCaptureDS *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(VideoCaptureDSClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : VideoCaptureDSClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *VideoCaptureDSClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(VideoCaptureDSClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	VideoCaptureDSClass::Additional Methods
} //	namespace
